[workspace]

members = [
    "v8-ui-app-poc",
    "http-bench-json-ops",
    "http-bench-json-ops-winit",
    "tokio-js-runtime-poc",
    "js-runtime",
    "deno-runtime-poc",
    "js-runtime-deno",
    "gui-runtime",
    "poc",
]